2017-10-01 16:35 UTC Viktor Szakats (vszakats users.noreply.github.com)   * .travis.yml     + start brew via travis_retry     % stop installing some dependencies via MXE to try fitting into       the 50 minutes time-slot     * restore qt for native macOS builds, there is plenty of time there
  * contrib/xhb/hbcompat.ch
  * contrib/xhb/xhb.hbp
  * contrib/xhb/xhb.hbx
  + contrib/xhb/xhberr2.c
    + add xHarbour Error() function. It's just a shorter alias for
      Cl*pper's ErrorNew()

  * package/mpkg_win.sh
    * cleanups
    + display a warning if GITHUB_TOKEN is undefined

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -99,23 +99,24 @@ before_install:
         sh -c "${DOCKER_SCRIPT}"
     elif [ "$TRAVIS_OS_NAME" = 'osx' ]; then
       if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
-        time brew install --force-bottle p7zip mingw-w64 jq osslsigncode dos2unix gpg coreutils || true
-        time brew install --force-bottle --build-bottle wine || true
+        time travis_retry brew install --force-bottle p7zip mingw-w64 jq osslsigncode dos2unix gpg coreutils || true
+        time travis_retry brew install --force-bottle --build-bottle wine || true
         export DISPLAY=:1
         time wineboot
         export MXE_DONT_INSTALL=gcc
       # travis_wait time ./package/mpkg_win_dl_mxe.sh \
       #   mxe-{i686,x86-64}-w64-mingw32.static-{bzip2,expat,libharu,mxml,libpng,lzo,minizip,pcre,sqlite,zlib}
+      # travis_wait time ./package/mpkg_win_dl_mxe.sh \
+      #   mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql} \
+      #   mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd}
         travis_wait time ./package/mpkg_win_dl_mxe.sh \
-          mxe-{i686,x86-64}-w64-mingw32.shared-pcre2 \
-          mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql} \
-          mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd}
+          mxe-{i686,x86-64}-w64-mingw32.shared-pcre2
       else
-      # brew install pcre qt zlib
-        brew install --force-bottle --build-bottle fontconfig || true
-        brew install --force-bottle \
+      # travis_retry brew install pcre zlib
+        travis_retry brew install --force-bottle --build-bottle fontconfig || true
+        travis_retry brew install --force-bottle \
           bzip2 expat libharu liblzf libmxml libpng libxdiff lzo minizip pcre2 sqlite \
-          cairo curl freeimage gd ghostscript icu4c libmagic libyaml mariadb ncurses openssl@1.1 postgresql rabbitmq-c s-lang unixodbc
+          cairo curl freeimage gd ghostscript icu4c libmagic libyaml mariadb ncurses openssl@1.1 postgresql qt rabbitmq-c s-lang unixodbc
       fi
       export MACOSX_DEPLOYMENT_TARGET=10.10
     fi
