.travis.yml: time more preparation steps [ci skip]

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -122,19 +122,19 @@ before_install:
         [ "${CC}" = 'mingw-clang' ] && _clang='llvm'
         time travis_retry brew install --force-bottle p7zip mingw-w64 ${_clang} jq osslsigncode dos2unix gpg
         time travis_retry brew install --force-bottle --build-bottle wine
-        wineboot --init
+        time wineboot --init
         export MXE_DONT_INSTALL=gcc
-      # travis_wait time ./package/mpkg_win_dl_mxe.sh \
+      # time travis_wait ./package/mpkg_win_dl_mxe.sh \
       #   mxe-{i686,x86-64}-w64-mingw32.static-{bzip2,expat,libharu,libpng,lzo,minizip,mxml,pcre,sqlite,zlib}
-      # travis_wait time ./package/mpkg_win_dl_mxe.sh \
+      # time travis_wait ./package/mpkg_win_dl_mxe.sh \
       #   mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql} \
       #   mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd}
-        travis_wait time ./package/mpkg_win_dl_mxe.sh \
+        time travis_wait ./package/mpkg_win_dl_mxe.sh \
           mxe-{i686,x86-64}-w64-mingw32.shared-pcre2
       else
-      # travis_retry brew install pcre zlib
-        travis_retry brew install --force-bottle --build-bottle fontconfig || true
-        travis_retry brew install --force-bottle \
+      # time travis_retry brew install pcre zlib
+        time travis_retry brew install --force-bottle --build-bottle fontconfig || true
+        time travis_retry brew install --force-bottle \
           bzip2 expat libharu libmxml libpng lzo minizip pcre2 sqlite \
           cairo curl freeimage gd ghostscript icu4c libmagic libyaml mariadb ncurses openssl@1.1 postgresql qt rabbitmq-c s-lang unixodbc
       fi
